# Generated by Django 3.1.1 on 2020-09-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='foto_categoria',
            field=models.ImageField(blank=True, upload_to='fotos/categorias/%d/%m/%Y/'),
        ),
        migrations.AddField(
            model_name='categorias',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
