# Generated by Django 3.1.1 on 2020-09-10 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('design_produto', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('data_produto', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('tamanho_pequeno', models.CharField(max_length=50)),
                ('tamanho_medio', models.CharField(max_length=50)),
                ('tamanho_grande', models.CharField(max_length=50)),
                ('tamanho_gigante', models.CharField(max_length=50)),
                ('cor_preto', models.CharField(max_length=20)),
                ('cor_azul', models.CharField(max_length=20)),
                ('cor_branco', models.CharField(max_length=20)),
                ('cor_vermelho', models.CharField(max_length=20)),
            ],
        ),
    ]
