# Generated by Django 3.1.1 on 2020-09-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0004_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho_um', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=5, verbose_name='Status')),
                ('tamanho_dois', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=5, verbose_name='Status')),
                ('tamanho_tres', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=5, verbose_name='Status')),
                ('tamanho_quatro', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=5, verbose_name='Status')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cor_azul',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cor_branco',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cor_cinza',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cor_preto',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tamanho_gigante',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tamanho_grande',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tamanho_medio',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tamanho_pequeno',
        ),
    ]
