# Generated by Django 3.1.1 on 2020-09-12 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0005_auto_20200912_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('design_produto', models.TextField()),
                ('data_produto', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('tamanho_um', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=5, verbose_name='Status')),
                ('tamanho_dois', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=5, verbose_name='Status')),
                ('tamanho_tres', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=5, verbose_name='Status')),
                ('tamanho_quatro', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=5, verbose_name='Status')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Tamanho',
        ),
    ]
