# Generated by Django 3.1.1 on 2020-09-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0006_auto_20200912_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='nome_categoria',
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho_dois',
            field=models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=5, verbose_name='Tamanhos'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho_quatro',
            field=models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=5, verbose_name='Tamanhos'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho_tres',
            field=models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=5, verbose_name='Tamanhos'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho_um',
            field=models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=5, verbose_name='Tamanhos'),
        ),
    ]
