# Generated by Django 3.1.1 on 2020-09-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0007_auto_20200912_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagem',
            field=models.ImageField(upload_to='static/img/agora'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(choices=[('Blusa de Moletom', 'Blusa de Moletom'), ('Calça de Sarja', 'Calça de Sarja'), ('Camisetas', 'Camisetas'), ('Bonés', 'Bonés'), ('Blusa corta-vento', 'Blusa corta-vento'), ('Calça de Moletom', 'Calça de Moletom'), ('Acessórios', 'Acessórios'), ('Jaquetas', 'Jaquetas'), ('Calçados', 'Calçados')], max_length=50, verbose_name='Categoria'),
        ),
    ]
