# Generated by Django 3.1.1 on 2020-09-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0008_auto_20200912_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagem',
            field=models.ImageField(upload_to='goldenbear/static/img/agora'),
        ),
    ]
