# Generated by Django 3.1.1 on 2020-09-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0011_auto_20200912_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nome_categoria',
            field=models.CharField(choices=[('Blusa de Moletom', 'Blusa de Moletom'), ('Calça de Sarja', 'Calça de Sarja'), ('Camisetas', 'Camisetas'), ('Bonés', 'Bonés'), ('Blusa corta-vento', 'Blusa corta-vento'), ('Calça de Moletom', 'Calça de Moletom'), ('Acessórios', 'Acessórios'), ('Jaquetas', 'Jaquetas'), ('Calçados', 'Calçados')], max_length=50, unique=True, verbose_name='Categoria'),
        ),
    ]
