# Generated by Django 3.1.1 on 2020-09-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0012_auto_20200912_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagem',
            field=models.ImageField(null=True, upload_to='images/produtos'),
        ),
    ]
