# Generated by Django 3.1.1 on 2020-09-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0015_auto_20200912_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tamanho_dois',
            field=models.CharField(blank=True, default='M', max_length=5, verbose_name='Tamanhos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tamanho_quatro',
            field=models.CharField(blank=True, default='GG', max_length=5, verbose_name='Tamanhos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tamanho_tres',
            field=models.CharField(blank=True, default='G', max_length=5, verbose_name='Tamanhos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tamanho_um',
            field=models.CharField(blank=True, default='P', max_length=5, verbose_name='Tamanhos'),
        ),
    ]
