# Generated by Django 3.1.1 on 2020-09-13 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('golden', '0016_auto_20200912_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nome_categoria',
        ),
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='categorias.categorias'),
            preserve_default=False,
        ),
    ]
