# Generated by Django 3.1.1 on 2020-09-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0018_auto_20200913_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
