# Generated by Django 3.1.1 on 2020-09-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0019_product_publicada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imagem',
        ),
        migrations.AddField(
            model_name='product',
            name='foto_produto',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
