# Generated by Django 3.1.1 on 2020-09-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('email2', models.EmailField(max_length=60, unique=True)),
                ('senha', models.CharField(max_length=20)),
                ('senha2', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=8)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=30)),
                ('data_de_nascimento', models.DateField(blank=True)),
                ('cpf', models.CharField(default='CPF não informado', max_length=11)),
                ('telefone', models.CharField(default='Telefone não informado', max_length=11)),
                ('celular', models.CharField(max_length=12)),
            ],
        ),
    ]
