# Generated by Django 3.1.1 on 2020-09-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('email2', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=20)),
                ('senha2', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('nascimento', models.DateField(blank=True)),
                ('cpf', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
            ],
        ),
    ]
